Add traditional chinese
Jerozgen/LanguageReload pull request #20
Opened 2022-12-04 17:04 UTC by xMikux

2022-12-04 17:08 UTC, xMikux commented
Wait, I notice I forgot translate some new text.
I will update later.

2022-12-04 17:29 UTC, xMikux commented
OK 👍

2022-12-06 03:15 UTC, Jerozgen requested changes

2022-12-06 03:15 UTC, Jerozgen commented on src/main/resources/assets/languagereload/lang/zh_tw.json
> +  "options.languagereload.title": "語言重新載入選項",
"Language Reload" is the mod name here; it should not be translated (as "Minecraft" in the first string).

2022-12-06 16:07 UTC, Jerozgen approved these changes

2022-12-06 16:08 UTC, merged